// Common business data
const businesses = [
    {
        id: 1,
        name: "Elite Injector Services",
        location: "Chicago, IL",
        rating: 5,
        image: "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
        description: "Elite Injector Services has been providing professional fuel injector cleaning and testing services since 2005. They specialize in ultrasonic cleaning and precision flow testing for all types of fuel injectors.",
        address: "123 Auto Row, Chicago, IL 60601",
        phone: "(312) 555-1234",
        website: "https://www.eliteinjectorservices.com",
        services: ["Ultrasonic Cleaning", "Flow Testing", "Injector Rebuilding", "Performance Tuning"]
    },
    {
        id: 2,
        name: "Precision Fuel Systems",
        location: "Dallas, TX",
        rating: 5,
        image: "https://images.unsplash.com/photo-1493238792000-8113da705763?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
        description: "Precision Fuel Systems offers comprehensive fuel system services with a focus on injector cleaning and diagnostics. Their state-of-the-art equipment ensures optimal performance restoration for all vehicle makes and models.",
        address: "456 Mechanic Street, Dallas, TX 75201",
        phone: "(214) 555-5678",
        website: "https://www.precisionfuelsystems.com",
        services: ["Fuel System Cleaning", "Injector Testing", "Diagnostic Services", "Component Replacement"]
    },
    {
        id: 3,
        name: "Advanced Injector Clinic",
        location: "Los Angeles, CA",
        rating: 4,
        image: "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
        description: "Advanced Injector Clinic specializes in performance vehicle fuel system maintenance with focus on European and sports cars. Their technicians are certified with regular training on the latest injector technologies.",
        address: "789 Performance Drive, Los Angeles, CA 90001",
        phone: "(323) 555-9012",
        website: "https://www.advancedinjector.com",
        services: ["Performance Tuning", "Ultrasonic Cleaning", "European Vehicle Specialists", "Fuel System Diagnostics"]
    },
    {
        id: 4,
        name: "Fuel System Specialists",
        location: "Miami, FL",
        rating: 4,
        image: "https://images.unsplash.com/photo-1597762470788-80269fd65fa0?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
        description: "Fuel System Specialists has been serving the Miami area for over 15 years with complete fuel injector cleaning and rebuilding services. Their facility includes the latest diagnostic and cleaning technology.",
        address: "101 Marina Way, Miami, FL 33101",
        phone: "(305) 555-3456",
        website: "https://www.fuelsystemspecialists.com",
        services: ["Marine Injector Service", "Automotive Injector Cleaning", "Diagnostic Testing", "Electronic Component Repair"]
    },
    {
        id: 5,
        name: "Injector Pros",
        location: "Seattle, WA",
        rating: 5,
        image: "https://images.unsplash.com/photo-1613214149366-3b28a2efd8e2?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
        description: "Injector Pros is Seattle's premier fuel injector service provider, focusing on exceptional customer service and technical expertise. Their facility offers full-service injector cleaning with same-day options available.",
        address: "222 Pacific Highway, Seattle, WA 98101",
        phone: "(206) 555-7890",
        website: "https://www.injectorpros.com",
        services: ["Same-Day Service", "Drivability Diagnostics", "Component Testing", "Full Injector Rebuilding"]
    },
    {
        id: 6,
        name: "Clean Flow Injector Service",
        location: "Denver, CO",
        rating: 4,
        image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
        description: "Clean Flow Injector Service specializes in high-altitude vehicle performance optimization and fuel system cleaning. Their unique approach addresses the specific needs of vehicles operating in mountainous regions.",
        address: "333 Mountain View Drive, Denver, CO 80201",
        phone: "(303) 555-0123",
        website: "https://www.cleanflowinjectors.com",
        services: ["High-Altitude Tuning", "Preventative Maintenance", "Complete Flow Testing", "Pattern Analysis"]
    },
    {
        id: 7,
        name: "Ultrasonic Injector Cleaning",
        location: "Atlanta, GA",
        rating: 5,
        image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
        description: "Ultrasonic Injector Cleaning uses advanced ultrasonic technology for deep cleaning and restoration of all injector types. Their comprehensive approach includes pre-cleaning testing and post-service verification.",
        address: "444 Peachtree Street, Atlanta, GA 30301",
        phone: "(404) 555-4567",
        website: "https://www.ultrasonicinjectors.com",
        services: ["Industrial-Grade Ultrasonic Cleaning", "Complete Flow Rate Testing", "Spray Pattern Analysis", "Electrical Testing"]
    },
    {
        id: 8,
        name: "Performance Fuel Systems",
        location: "Phoenix, AZ",
        rating: 4,
        image: "https://images.unsplash.com/photo-1537358161533-f74f1e596aa4?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
        description: "Performance Fuel Systems focuses on high-performance and racing applications with specialized services for modified vehicles. Their team includes former race mechanics with extensive experience in fuel system optimization.",
        address: "555 Desert Road, Phoenix, AZ 85001",
        phone: "(602) 555-8901",
        website: "https://www.performancefuelsystems.com",
        services: ["Racing Injector Services", "High-Flow Testing", "Performance Tuning", "Custom Modifications"]
    }
];

// Common cities for search suggestions
const cities = [
    "New York, NY",
    "Los Angeles, CA",
    "Chicago, IL",
    "Houston, TX",
    "Phoenix, AZ",
    "Philadelphia, PA",
    "San Antonio, TX",
    "San Diego, CA",
    "Dallas, TX",
    "San Jose, CA",
    "Austin, TX",
    "Jacksonville, FL",
    "Fort Worth, TX",
    "Columbus, OH",
    "Charlotte, NC",
    "San Francisco, CA",
    "Indianapolis, IN",
    "Seattle, WA",
    "Denver, CO",
    "Washington, DC",
    "Boston, MA",
    "El Paso, TX",
    "Nashville, TN",
    "Detroit, MI",
    "Oklahoma City, OK",
    "Portland, OR",
    "Las Vegas, NV",
    "Memphis, TN",
    "Louisville, KY",
    "Baltimore, MD",
    "Milwaukee, WI",
    "Albuquerque, NM",
    "Tucson, AZ",
    "Fresno, CA",
    "Sacramento, CA",
    "Mesa, AZ",
    "Kansas City, MO",
    "Atlanta, GA",
    "Miami, FL",
    "Omaha, NE",
    "Raleigh, NC",
    "Colorado Springs, CO",
    "Long Beach, CA",
    "Virginia Beach, VA",
    "Oakland, CA",
    "Minneapolis, MN",
    "Tampa, FL",
    "Arlington, TX",
    "New Orleans, LA",
    "Cleveland, OH"
];
